# Generated by Django 5.0.7 on 2024-09-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('savings', 'savings'), ('current', 'current')], max_length=100),
        ),
    ]
