# Generated by Django 5.0.7 on 2024-09-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'withdraw'), ('transfer_money', 'transfer_money'), ('loan', 'loan'), ('deposit', 'deposit')], max_length=100),
        ),
    ]
