# Generated by Django 5.0.7 on 2024-09-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='time',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'withdraw'), ('deposit', 'deposit'), ('transfer_money', 'transfer_money'), ('loan', 'loan')], max_length=100),
        ),
    ]
