# Generated by Django 5.0.7 on 2024-09-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_transaction_amount_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='loan_approve',
            new_name='transaction_status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='balance_after_transaction',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[(2, 'Loan Paid'), (4, 'withdraw'), (5, 'transfer_money'), (1, 'loan'), (3, 'deposit')], max_length=100),
        ),
    ]
