# Generated by Django 5.0.7 on 2024-09-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_loan_approve_transaction_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'withdraw'), ('loan_paid', 'loan_paid'), ('deposit', 'deposit'), ('loan', 'loan'), ('transfer_money', 'transfer_money')], max_length=100),
        ),
    ]
