# Generated by Django 5.0.7 on 2024-09-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('loan_paid', 'loan_paid'), ('withdraw', 'withdraw'), ('transfer_money', 'transfer_money'), ('deposit', 'deposit'), ('loan', 'loan')], max_length=100),
        ),
    ]
