# Generated by Django 5.0.7 on 2024-09-21 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_account_type'),
        ('transactions', '0008_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'withdraw'), ('loan', 'loan'), ('transfer_money', 'transfer_money'), ('deposit', 'deposit'), ('loan_paid', 'loan_paid')], max_length=100),
        ),
    ]
