# Generated by Django 5.0.7 on 2024-09-21 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_transaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('loan_paid', 'loan_paid'), ('deposit', 'deposit'), ('loan', 'loan'), ('withdraw', 'withdraw'), ('transfer_money', 'transfer_money')], max_length=100),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_type', models.CharField(choices=[('car_loan', 'car_loan'), ('other', 'other'), ('home_loan', 'home_loan'), ('bussiness_loan', 'business_loan')], max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
