# Generated by Django 5.0.7 on 2024-09-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_transaction_transaction_type_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('other', 'other'), ('bussiness_loan', 'business_loan'), ('home_loan', 'home_loan'), ('car_loan', 'car_loan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('transfer_money', 'transfer_money'), ('loan', 'loan'), ('withdraw', 'withdraw'), ('loan_paid', 'loan_paid')], max_length=100),
        ),
    ]
