# Generated by Django 5.0.7 on 2024-09-21 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_loan_loan_status_alter_loan_loan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('bussiness_loan', 'business_loan'), ('other', 'other'), ('home_loan', 'home_loan'), ('car_loan', 'car_loan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('loan_paid', 'loan_paid'), ('loan', 'loan'), ('deposit', 'deposit'), ('transfer_money', 'transfer_money'), ('withdraw', 'withdraw')], max_length=100),
        ),
    ]
