# Generated by Django 5.0.7 on 2024-09-21 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_loan_date_created_alter_loan_loan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('car_loan', 'car_loan'), ('bussiness_loan', 'business_loan'), ('home_loan', 'home_loan'), ('other', 'other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('loan_paid', 'loan_paid'), ('withdraw', 'withdraw'), ('deposit', 'deposit'), ('loan', 'loan'), ('transfer_money', 'transfer_money')], max_length=100),
        ),
    ]
