# Generated by Django 5.0.7 on 2024-09-21 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_loan_amount_alter_loan_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('other', 'other'), ('car_loan', 'car_loan'), ('home_loan', 'home_loan'), ('bussiness_loan', 'business_loan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('loan_paid', 'loan_paid'), ('withdraw', 'withdraw'), ('transfer_money', 'transfer_money'), ('loan', 'loan'), ('deposit', 'deposit')], max_length=100),
        ),
    ]
