# Generated by Django 5.0.7 on 2024-10-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_loan_date_created_alter_loan_loan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('bussiness_loan', 'business_loan'), ('personal_loan', 'personal_loan'), ('other', 'other'), ('car_loan', 'car_loan'), ('home_loan', 'home_loan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'withdraw'), ('transfer_money', 'transfer_money'), ('loan_paid', 'loan_paid'), ('deposit', 'deposit'), ('loan', 'loan')], max_length=100),
        ),
    ]
